=== tapis-project/tapispy/docs/_static/schema/System.json
{
  "$id": "http://agavepy.readthedocs.io/en/latest/System.json", 
  "$schema": "http://json-schema.org/draft-07/schema#", 
  "properties": {
    "default": {
      "description": "Is the system the default for the authenticated user?", 
      "type": "boolean"
    }, 
    "description": {
      "description": "Verbose description of this system.", 
      "type": "string"
    }, 
    "environment": {
      "description": "Environment variables to set upon login prior to job submission.", 
      "type": "string"
    }, 
    "executionType": {
      "description": "The execution paradigm used to run jobs on this system.", 
      "enum": [
        "HPC", 
        "CONDOR", 
        "CLI"
      ], 
      "type": "string"
    }, 
    "id": {
      "description": "Unique identifier for this system.", 
      "type": "string"
    }, 
    "lastModified": {
      "description": "The date this system was last modified in ISO 8601 format.", 
      "type": "string"
    }, 
    "login": {
      "description": "The login config defining how to connect to this system for job submission.", 
      "type": "LoginConfig"
    }, 
    "maxSystemJobs": {
      "description": "The maximum number of jobs that can be simultaneously run on the system across all queues.", 
      "type": "int"
    }, 
    "maxSystemJobsPerUser": {
      "description": "The maximum number of jobs that can be simultaneously run on the system across all queues by a single user.", 
      "type": "int"
    }, 
    "name": {
      "description": "Common name for this system.", 
      "type": "string"
    }, 
    "public": {
      "description": "Is the system publicly available?", 
      "type": "boolean"
    }, 
    "queues": {
      "description": "The execution paradigm used to run jobs on this system.", 
      "type": "array"
    }, 
    "revision": {
      "description": "The number of times this app has been updated.", 
      "type": "int"
    }, 
    "scheduler": {
      "description": "The type of scheduled used to run jobs.", 
      "enum": [
        "COBALT", 
        "CONDOR", 
        "FORK", 
        "LOADLEVELER", 
        "LSF", 
        "MOAB", 
        "PBS", 
        "SGE", 
        "SLURM", 
        "TORQUE", 
        "UNKNOWN"
      ], 
      "type": "string"
    }, 
    "scratchDir": {
      "description": "The scratch directory where job execution directories will be created at runtime. The workDir is used if this is not specified.", 
      "type": "string"
    }, 
    "site": {
      "description": "The site associated with this system.", 
      "type": "string"
    }, 
    "startupScript": {
      "description": "Script to be run after login and prior to execution.", 
      "type": "string"
    }, 
    "status": {
      "description": "The status of this system. Systems must be in UP status to be used.", 
      "enum": [
        "UP", 
        "DOWN", 
        "UNKNOWN"
      ], 
      "type": "string"
    }, 
    "storage": {
      "description": "The storage config defining how to connect to this system for data staging.", 
      "type": "StorageConfig"
    }, 
    "type": {
      "description": "The type of this system.", 
      "enum": [
        "EXECUTION", 
        "STORAGE"
      ], 
      "type": "string"
    }, 
    "uuid": {
      "description": "The uuid of this system.", 
      "type": "string"
    }, 
    "workDir": {
      "description": "The work directory where job execution directories will be created at runtime. This is used if scratchDir is not specified. If neither are specified, the job directory will be created in the system homeDir.", 
      "type": "string"
    }
  }, 
  "required": [], 
  "title": "AgavePy System schema", 
  "type": "object"
}

=== tapis-project/tapispy/tapispy/tests/test-storage.json
{
   "id": "endofday.staging.storage",
   "name": "endofday staging storage system",
   "status":"UP",
   "type":"STORAGE",
   "description":"Storage system for endofday runs in the staging environment.",
   "site":"agaveapi.co",
   "storage":{
      "host":"52.21.60.210",
      "port":22,
      "protocol":"SFTP",
      "rootDir":"/",
      "homeDir":"/home/ubuntu",
      "auth":{
         "username":"ubuntu",
         "publicKey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBQEVi4kY8430rMCr8BsXnDrgskQzVdZiN1SP8feJKjKfwpNaJ1okwKq1E1OkA3AcnM/CiLBh6fsGGpVDtYgjXwcrhxHPnanzmkcJveSHAR3eT1F37D+1tufMHn1dSGtya1SpHUr4Pape1jh4Yk53TIgqJWHskDM8KajBFevMVLsofd+NL+/Knz6FWT2/lgJIndNPhA9oCjcikZn79YoEeYVRQPBkvtemhPBvSXF8Dw/Am3ZMgXgENxMHRgHLNC3/byZS+54YW27tOSjZb+7ifkFNA1kfE7ycas4l6DJkLLMj9E9QDy8irtPo8s2qo2YENXZfhd5DR6YW58VJ+t/5x ec2-eod-compute",
         "privateKey": "",
         "type": "SSHKEYS"
      }
   }
}

=== tapis-project/tapispy/tapispy/tests/test-compute.json
{
	"id": "endofday.staging.execute",
	"name": "endofday staging execution system",
	"status": "UP",
	"type": "EXECUTION",
	"description": "Execution system for endofday runs in the staging environment.",
	"site": "agaveapi.co",
	"executionType": "CLI",
    "scratchDir": "/scratch",
    "workDir": "/work",
   "queues": [
     {
       "name": "debug",
       "maxJobs": 100,
       "maxUserJobs": 10,
       "maxNodes": 128,
       "maxMemoryPerNode": "2GB",
       "maxProcessorsPerNode": 128,
       "maxRequestedTime": "24:00:00",
       "customDirectives": "",
       "default": true
     }
   ],
   "login":{
      "host":"52.21.60.210",
      "port": 22,
      "protocol": "SSH",
      "scratchDir": "/scratch",
      "workDir": "/work",
      "auth":{
         "username":"ubuntu",
         "publicKey":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBQEVi4kY8430rMCr8BsXnDrgskQzVdZiN1SP8feJKjKfwpNaJ1okwKq1E1OkA3AcnM/CiLBh6fsGGpVDtYgjXwcrhxHPnanzmkcJveSHAR3eT1F37D+1tufMHn1dSGtya1SpHUr4Pape1jh4Yk53TIgqJWHskDM8KajBFevMVLsofd+NL+/Knz6FWT2/lgJIndNPhA9oCjcikZn79YoEeYVRQPBkvtemhPBvSXF8Dw/Am3ZMgXgENxMHRgHLNC3/byZS+54YW27tOSjZb+7ifkFNA1kfE7ycas4l6DJkLLMj9E9QDy8irtPo8s2qo2YENXZfhd5DR6YW58VJ+t/5x ec2-eod-compute",
         "privateKey":"",
         "type":"SSHKEYS"
      }
   },
   "storage":{
      "host":"52.21.60.210",
      "port":22,
      "protocol":"SFTP",
      "rootDir":"/",
      "homeDir":"/home/ubuntu",
      "auth":{
         "username":"ubuntu",
         "publicKey":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBQEVi4kY8430rMCr8BsXnDrgskQzVdZiN1SP8feJKjKfwpNaJ1okwKq1E1OkA3AcnM/CiLBh6fsGGpVDtYgjXwcrhxHPnanzmkcJveSHAR3eT1F37D+1tufMHn1dSGtya1SpHUr4Pape1jh4Yk53TIgqJWHskDM8KajBFevMVLsofd+NL+/Knz6FWT2/lgJIndNPhA9oCjcikZn79YoEeYVRQPBkvtemhPBvSXF8Dw/Am3ZMgXgENxMHRgHLNC3/byZS+54YW27tOSjZb+7ifkFNA1kfE7ycas4l6DJkLLMj9E9QDy8irtPo8s2qo2YENXZfhd5DR6YW58VJ+t/5x ec2-eod-compute",
         "privateKey":"",
         "type":"SSHKEYS"
      }
   },
   "maxSystemJobs": 100,
   "maxSystemJobsPerUser": 10,
   "scheduler": "FORK",
   "environment": "",
   "startupScript": "./bashrc"
}
